"""
Django settings for bank_ledger_project project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
HOST = os.environ.get("SERVER_HOSTNAME") or "localhost"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+^=ss-mqfu&9w!!eongtbylbp3)5_^xx*5cp2#!@n*atu@-ioa'
OWN_BANK_IP = os.environ.get("SERVER_HOSTNAME") or "localhost"
OTHER_BANK_IP = os.environ.get("OTHER_BANK_HOST") or "localhost"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["127.0.0.1", HOST]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bank_ledger_app',
    'api',
    'rest_framework',
    #2FA
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
    #Cron jobs and queues
    'django_rq',
    'django_crontab',
]


CSRF_TRUSTED_ORIGINS = [
    f"http://{HOST}.localhost",
    f"http://{HOST}"
    "http://localhost"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    #2FA
     
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    ###
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'bank_ledger_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'tf_tags': 'bank_ledger_app.templatetags.tf_tags'
            }
        },
    },
]

WSGI_APPLICATION = 'bank_ledger_project.wsgi.application'



# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'database/db.sqlite3'),
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': 'redis-server',
        'PORT': '6379',
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Copenhagen'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

CRONJOBS = [
    ('0 0 1 * *', 'bank_ledger_app.cron.add_late_fee', '>> /tmp/add_late_fee.log'),
    ('0 0 1 * *', 'bank_ledger_app.cron.add_interest', '>> /tmp/add_interest.log'),
    ('* * * * *', 'bank_ledger_app.cron.recusive_payment', '>> /tmp/recusive_payment.log')
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL= 'two_factor:login' 
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'two_factor:login' 
