# Generated by Django 4.1.1 on 2022-10-07 17:31

from django.db import migrations, models
import django.db.models.deletion
import uuid
import os


class Migration(migrations.Migration):

    initial = True

    # Creating superuser when DB is created
    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        superuser = User.objects.create_superuser(
            username='admin',
            email='admin@admin',
            password='123'
        )

        superuser.save()

    # This ensures that a 'customer' and an 'account' with this information exists anytime the DB is created
    def create_bank_account(apps, schema_editor):
        Customer = apps.get_model('bank_ledger_app', 'Customer')
        Account = apps.get_model('bank_ledger_app', 'Account')
        AuthUser = apps.get_model('auth', 'User')

        bank_user = AuthUser(id=1, username="bank_user", password="temp_password", is_staff=True, is_active=True)
        bank_user.save()

        bank = Customer(
            customer_id="40c49b66-8eb1-499b-a914-48f60dd48b7b",
            email='bank@bankaccount.bank',
            rank="Super",
            phone_number="illegal_num",
            # user=bank_user - Not needed as it defaults to user.id = 1 and that is hard defined above
        )
        bank.save()
        bank_account = Account(
            account_id="5bc6860e-61c2-4427-b9d8-b21c80c8370d",
            account_name="Bank Loan Account",
            customer=bank
        )
        bank_account.save()

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(default='Main Account', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rank', models.CharField(choices=[('Base', 'Base'), ('Silver',
                 'Silver'), ('Gold', 'Gold')], default='Base', max_length=6)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=254, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='ledger_destination', to='bank_ledger_app.account')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                 related_name='ledger_origin', to='bank_ledger_app.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank_ledger_app.customer'),
        ),
        migrations.RunPython(create_bank_account),
        migrations.RunPython(generate_superuser),
    ]

