# Generated by Django 4.1.1 on 2022-10-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_ledger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='loan_id',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank_ledger_app.ledger'),
        ),
    ]
