# Generated by Django 4.1.1 on 2022-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_ledger_app', '0006_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='destination',
            field=models.UUIDField(),
        ),
    ]
