# Generated by Django 4.1.3 on 2022-12-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_ledger_app', '0006_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='months',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
