# Generated by Django 4.1.5 on 2023-01-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_ledger_app", "0007_alter_ledger_destination"),
        ("bank_ledger_app", "0008_ledger_months"),
    ]

    operations = []
