# Generated by Django 4.1.1 on 2022-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_bank_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('other_bank_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('own_account_id', models.UUIDField()),
                ('other_account_id', models.UUIDField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferFunds',
            fields=[
                ('transaction_id', models.UUIDField(primary_key=True, serialize=False)),
                ('origin_id', models.UUIDField()),
                ('destination_id', models.UUIDField()),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
