# Generated by Django 4.1.1 on 2022-12-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferfunds',
            old_name='destination_id',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='transferfunds',
            old_name='origin_id',
            new_name='origin',
        ),
    ]
