# Generated by Django 4.1.5 on 2023-01-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_destination_id_transferfunds_destination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="other_bank_ip",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="own_bank_ip",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
